default_platform(:android)

platform :android do
  desc 'Upload the release AAB to Google Play (internal track by default)'
  lane :play_upload do
    supply(
      package_name: ENV.fetch('PACKAGE_NAME', 'com.seiko.keystoreviewer'),
      json_key: ENV.fetch('PLAY_SERVICE_ACCOUNT_JSON'),
      aab: ENV.fetch('AAB_PATH'),
      track: ENV.fetch('PLAY_TRACK', 'internal'),
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
